# .air.yaml
root: "."
tmp_dir: "tmp"

build:
  # 核心：每次热加载前执行 sqlc 生成
  pre_cmd:
    - "sqlc generate"
  # 编译指令
  cmd: "go build -o server.exe ./main.go"
  # 编译后的二进制运行指令
  bin: "./tmp/main.exe"
  # 监听的文件后缀
  include_ext: ["go", "yaml", "yml", "sql", "toml"]
  # 忽略的目录
  exclude_dir: ["assets", "tmp", "vendor", "database/migrations"]
  # 监听文件修改后的延迟（毫秒）
  delay: 1000
  # 发生构建错误时停止运行旧的二进制文件
  stop_on_error: true

log:
  time: true
  filenane: "logs/app.log"
  max_size: 10
  max_age: 30
  max_backups: 3
  compress: true

color:
  main: "magenta"
  watcher: "cyan"
  build: "yellow"
  runner: "green"